### ISSUE TITLE
Add Sample Code

### ISSUE THREAD

**Issue by Stoeoeoe** [edorasware/edoras-one-initializr#2]
Often, when creating a new project, it would be helpful to be provided with some boilerplate code, specifically:

- A class `CustomConfiguration` serving as a Spring Configuration under `com.edorasware.config.custom`
- A simple REST endpoint `DemoController` with a GET and POST RequestMapping under `com.example.demo.rest` which yield a simple ImmutableMap/JSON.
- A class `DemoRestConfiguration` under `com.example.demo.config` with a default `@ComponentScan` on `com.example.demo.rest`
- A class `CustomDispatcherConfiguration` under `com.edorasware.rest` which Imports the `DemoRestConfiguration` possibly along with required Addon DispatcherConfigurations 
- A folder `webapp` along with a `custom.css` file containing some basic customizations (ideally a custom logo), an `accounts.css` as well as a `custom.js` containing a simple service. Additionally, a folder `WEB-INF` containing a bare-bone `web.xml` file should be generated.
- A palette configuration `demo.process.palette.xml` under `com.edorasware.vis.palette` containing a `component-presentation`  which references a demo picture as well as a group and a simple custom service task component. The expression could be really simple as well and merely demonstrate the concepts.

Since there already is a flag "Generate Sample Code", I'd suggest that above files are only included if the flag is ticked.

**Comment by rvillars** [comment]
I generally agree. Some minor counterproposals:

- A new configuration endpoint for the dispatcher servlet will be introduced soon by edoras one (https://jira.edorasware.com/browse/CLD-12189). We should use this directly instead of creating a `CustomDispatcherConfiguration`.
- web.xml is a really outdated concept. Instead we should use the official extension points for widgets for projects (https://confluence.edorasware.com/display/EDWSVC/Addon+Concept#AddonConcept-ExtensionPoints) and add sample css/js code there. The widget-resource-addon will be part of the starter soon (or even part of edoras one itself).

**Comment by rvillars** [comment]
Fixed with https://github.com/edorasware/edoras-one-initializr/releases/tag/02-23-2018
